/**
 * Cloudflare Pages `_headers` for both projects (ADR-0005).
 *
 * Syntax (developers.cloudflare.com/pages/configuration/headers, checked
 * 2026-09-24): a URL pattern line, then indented `Name: value` lines; one
 * splat per pattern; every matching rule's headers are inherited and a
 * header set twice is comma-joined — so each header is defined by exactly
 * ONE matching rule here (a comma-joined CSP would be two policies).
 * Limits: 100 rules, 2,000 characters per line.
 */
import { STORY_CSP } from './policy.js'

const rule = (pattern, headers) =>
  `${pattern}\n${Object.entries(headers).map(([k, v]) => `  ${k}: ${v}`).join('\n')}\n`

const originList = (list) => [...new Set((list ?? []).filter(Boolean).map((o) => o.replace(/\/+$/, '')))]

/**
 * Headers for the stories (content-plane) project.
 * @param {{ appOrigins?: string[] }} o  exact app origins allowed to read registry/packages
 *   (CORS allows one origin per response; with several origins, or none known yet, `*` is used —
 *   the content is public, credential-free static files, so `*` leaks nothing — and the
 *   CSP frame-ancestors list still restricts who may frame story HTML).
 */
export function storiesHeaders({ appOrigins = [] } = {}) {
  const apps = originList(appOrigins)
  const allowOrigin = apps.length === 1 ? apps[0] : '*'
  const frameAncestors = apps.length ? ` frame-ancestors ${apps.join(' ')};` : ''
  return [
    '# Storyframe content plane — generated by packages/publishing/src/headers.js',
    rule('/*', {
      'Access-Control-Allow-Origin': allowOrigin,
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'no-referrer',
      ...(allowOrigin !== '*' ? { Vary: 'Origin' } : {}),
    }),
    // content-addressed releases never change — cache forever; story CSP on every file
    rule('/packages/*', {
      'Cache-Control': 'public, max-age=31536000, immutable',
      'Content-Security-Policy': `${STORY_CSP};${frameAncestors}`.replace(/;$/, ''),
    }),
    // channel pointers and the audit trail must always be fresh
    rule('/registry.json', { 'Cache-Control': 'no-cache' }),
    rule('/audit-log.json', { 'Cache-Control': 'no-cache' }),
    rule('/share/*', {
      'Cache-Control': 'public, max-age=300',
      'Content-Security-Policy': "default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'; base-uri 'none'",
    }),
  ].join('\n')
}

/**
 * Headers for the app (application-plane) project.
 * @param {{ storyOrigins?:string[], connectOrigins?:string[] }} o
 *   storyOrigins: where story frames load from ('self' covers single-origin mode)
 *   connectOrigins: extra fetch targets (Supabase URL; GitHub API is always allowed for the Admin Studio)
 */
export function appHeaders({ storyOrigins = [], connectOrigins = [] } = {}) {
  const stories = originList(storyOrigins)
  const connect = originList(['https://api.github.com', ...stories, ...connectOrigins])
  const csp = [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    `img-src 'self' data: blob: ${stories.join(' ')}`.trim(),
    "font-src 'self' data:",
    `connect-src 'self' ${connect.join(' ')}`.trim(),
    `frame-src 'self' blob: ${stories.join(' ')}`.trim(),
    "worker-src 'self'",
    "manifest-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ].join('; ')
  const security = {
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
  }
  // The CSP goes on the app DOCUMENT paths only (hash routing ⇒ "/" is the
  // only document). A "/*" CSP would also land on same-origin story HTML in
  // starter mode and block its inline scripts.
  return [
    '# Storyframe application plane — generated by packages/publishing/src/headers.js',
    rule('/*', security),
    rule('/', { 'Content-Security-Policy': csp, 'Cache-Control': 'no-cache' }),
    rule('/index.html', { 'Content-Security-Policy': csp, 'Cache-Control': 'no-cache' }),
    rule('/assets/*', { 'Cache-Control': 'public, max-age=31536000, immutable' }),
    rule('/config.json', { 'Cache-Control': 'no-cache' }),
    rule('/sw.js', { 'Cache-Control': 'no-cache' }),
  ].join('\n')
}

/**
 * Starter mode — one project serves the app AND /stories-host/. Every story
 * runs in the opaque sandbox (same origin ⇒ never allow-same-origin).
 */
export function singleOriginHeaders({ connectOrigins = [] } = {}) {
  const app = appHeaders({ storyOrigins: [], connectOrigins })
  return app + '\n' + [
    '# content plane, served under /stories-host/',
    rule('/stories-host/packages/*', {
      'Cache-Control': 'public, max-age=31536000, immutable',
      'Content-Security-Policy': `${STORY_CSP}; frame-ancestors 'self'`,
    }),
    rule('/stories-host/registry.json', { 'Cache-Control': 'no-cache' }),
    rule('/stories-host/audit-log.json', { 'Cache-Control': 'no-cache' }),
  ].join('\n')
}
